In [7]:
import numpy as np
np.set_printoptions(suppress=True, formatter={'float_kind': '{:0.1f}'.format})
from IPython.display import display

array1= np.arange(1, 16+1)
array1.shape=(4, 4)
display(array1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [17]:
array2= np.arange(10,50, 5)
array2.shape=(2,4)
display(array2)

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [30]:
rand_array1 = np.random.randint(1, 101, (3, 3))
display(rand_array1)
print("max:",rand_array1.max())
print("min:",rand_array1.min())

array([[51,  1, 58],
       [12,  3, 81],
       [92, 60, 40]])

max: 92
min: 1


In [40]:
array3= np.linspace(0,20, 10, dtype=int)
display(array3)
display(array3[0:5])
display(array3[0::2])
display(array3[::-1])


array([ 0,  2,  4,  6,  8, 11, 13, 15, 17, 20])

array([0, 2, 4, 6, 8])

array([ 0,  4,  8, 13, 17])

array([20, 17, 15, 13, 11,  8,  6,  4,  2,  0])

In [54]:
rand_array2 = np.random.randint(1, 51, (4, 5))
display(rand_array2)
print("second line:",rand_array2[1, :])
print("fourth row:",rand_array2[:, 3])

array([[24, 23, 12, 24, 20],
       [10, 47, 43,  2, 33],
       [ 7,  8, 12, 10, 10],
       [10, 17, 14, 22,  2]])

second line: [10 47 43  2 33]
fourth row: [24  2 10 22]


In [87]:
rand_array3 = np.random.randint(1, 101, (1, 15))
display(rand_array3)
print("the index of the smallest number is:",rand_array3.argmin())
print("the index of the biggest number is:",rand_array3.argmax())
# rand_array3_copy=rand_array3.copy()
# np.save("rand_array3_copy.npy",rand_array3_copy)
# rand_array3_saved=np.load("rand_array3_copy.npy")






array([[64, 96, 44, 14, 34, 93, 26, 55, 85, 91,  3, 73, 34,  3, 14]])

the index of the smallest number is: 10
the index of the biggest number is: 1


In [115]:
display(rand_array3_saved)
print("numbers that divided by 5:",rand_array3_saved[(rand_array3_saved % 5 == 0)])
print("numbers between 10 and 50:",rand_array3_saved[(10>rand_array3_saved)|(rand_array3_saved>50)])

array([[41, 47, 63, 40,  9, 52,  6,  7, 73, 19,  3, 51, 12, 19, 74]])

numbers that divided by 5: [40]
numbers between 10 and 50: [63  9 52  6  7 73  3 51 74]
